export const FETCH_COLLABORATORS_REQUEST = 'FETCH_COLLABORATORS_REQUEST';
export const FETCH_COLLABORATORS_SUCCESS = 'FETCH_COLLABORATORS_SUCCESS';
export const FETCH_COLLABORATORS_FAILURE = 'FETCH_COLLABORATORS_FAILURE';
